var commonFunc = require('./../methods/commonFunc');
module.exports = {
    constants: function() {
        return {
            PRODUCTNAME: 'autoProduct' + commonFunc.generateRandomNumber(),
            DESCRIPTION: 'automationTest',
            STARTDATE: new Date(Date.now()),
            INVALIDSTARTDATE: new Date(Date.now() + 1000 * 60 * 60 * 24),
            ENDDATE: new Date(Date.now() + 1000 * 60 * 60 * 24),
            TERMMONTH: 12,
            NUMOFCARDDIGITS: 14,
            POLICYTYPE: 'password',
            HOLDERNAME: 'autoHolder' + commonFunc.generateRandomNumber(),
            NONAMEBATCH: 'noName' + commonFunc.generateRandomNumber(),
            NAMEBATCH: 'name' + commonFunc.generateRandomNumber(),
            PAGESIZE: 1000,
            PAGENUMBER: 1,
            ASC: 'ASC',
            DESC: 'DESC',
            TEST1: 'test1',
            BATCHNAME: 'batchName',
            NUMBEROFCARDSTEXT: 'numberOfCrads',
            GENERATEDPINMAILS: 'generatedPinMails',
            DOWNLOADS: 'downloads',
            BATCHDATESENT: 'batchDateSent',
            BATCHDATECREATED: 'batchDateCreated',
            BATCHSTATUS: 'batchStatus',
            NAME: 'name',
            STARTDATETEXT: 'startDate',
            ENDDATETEXT: 'endDate',
            TYPENAME: 'typeName',
            BIN: 'bin',
            CARDNUMBERCONSTRUCTION: 'cardNumberConstruction',
            ACTIVESTATUS: 'isActive',
            CUSTOMERNAMETEXT: 'customerName',
            PERSONNAME: 'personName',
            TARGETBRANCHNAME: 'targetBranchName',
            APPLICATIONIDTEXT: 'applicationId',
            STATUSNAME: 'statusName',
            PRODUCTNAMETEXT: 'productName',
            CREATEDONTEXT: 'createdOn',
            TARGETBRANCHNAMETEXT: 'targetBranchName',
            ISSUINGBRANCHNAMETEXT: 'issuingBranchName',
            CARDNUMBERTEXT: 'cardnumber',
            CURRENTBRANCHNAMETEXT: 'currentBranchName',
            ISACTIVE1: 1,
            STATUSID1: 1,
            INVALIDSTATUSID: 0,
            INVALIDISACTIVE: 2,
            INVALIDTYPEID: 0,
            INVALIDPRODUCTID: 0,
            INVALIDAPPLICATIONID: 0,
            APPLICATIONID1: 1,
            TYPEID2: 2,
            CONTENT: '/9j/4AAQSkZJRgABAQEAeAB4AAD/2wBDAAIBAQIBAQICAgICAgICAwUDAwMDAwYEBAMFBwYHBwcGBwcICQsJCAgKCAcHCg0KCgsMDAwMBwkODw0MDgsMDAz/2wBDAQICAgMDAwYDAwYMCAcIDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAz/wAARCABSAJMDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD9/KKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooA//Z',
            ENCODING: 'base64',
            CONTENTTYPE: 'image/jpeg',
            APPLICATIONTEXT: 'Application'
        };
    }
};
